pipeline {
  agent any

  stages {
    
    stage('Deploy NGINX') {
      steps {
        bat 'docker run -d -p 80:80 --name my-nginx-container nginx'
      }
    }
    stage('Deploy Image') {
      steps {
        dir('client') {
          bat 'docker build --no-cache -t oussamarhouch/projet-jee:frontend .'
          bat 'docker login -u oussamarhouch -p Oussama2002.'
          bat 'docker pull oussamarhouch/projet-jee:frontend'
          bat 'docker push oussamarhouch/projet-jee:frontend'
        }
      }
    }
    
    
  }
}
