pipeline {
  agent any
  
  stages {
    stage('Build') {
      steps {
        dir('server') {
          bat 'mvn clean package'
        }
      }
    }
    
    stage('Test') {
      steps {
        dir('server') {
          bat 'mvn test'
        }
      }
    }
    
    stage('Deploy') {
      steps {
        dir('server') {
          bat 'docker build -t oussamarhouch/projet-jee:backend .'
          bat 'docker push oussamarhouch/projet-jee:backend'
        }
      }
    }
  }
}
