pipeline {
  agent any
  
  stages {
  
    
    stage('Build') {
      steps {
        bat '/server/mvn clean package'
      }
    }
    
    stage('Test') {
      steps {
        bat '/server/mvn test'
      }
    }
    
    stage('Deploy') {
      steps {
        bat '/server/mvn deploy'
      }
    }
  }
}
